parameters:
  AgentPool : 'Hosted macOS High Sierra'
  JobName: 'MacOS_CI_Dev'
  BuildCommand: ''
  DoNugetPack: 'false'
  NuPackScript: ''

jobs:
- job: ${{ parameters.JobName }}
  workspace:
    clean: all
  timeoutInMinutes:  120
  pool: ${{ parameters.AgentPool }}
  variables:
    BuildCommand: ${{ parameters.BuildCommand }}
  steps:
    - template: mac-set-variables-and-download.yml
    - template: mac-ci-build-and-test.yml
      parameters:
        BuildCommand: ${{ parameters.BuildCommand }}
        DoNugetPack: ${{ parameters.DoNugetPack }}
        NuPackScript: ${{ parameters.NuPackScript }}
        
