parameters:
  DoDebugBuild: 'true'
  DoCompliance: 'false'
  BuildCommand: ''
  JobName: 'Windows_CI_Dev'
  DoNugetPack:  'false'
  NuPackScript : ''
  ArtifactName: 'drop-nuget'
  DoEsrp: 'false'
  DoTestCoverage: 'false'
  BuildArch: 'x64'
  SetVcvars: 'false'
  msbuildArchitecture: 'amd64'
  MsbuildArguments: '/m'
  EnvSetupScript: 'setup_env.bat'
  CudaVersion: ''
  AgentPool: 'Win-CPU'
  AgentDemands: []
  OrtPackageId: Microsoft.ML.OnnxRuntime
jobs:
- job: ${{ parameters.JobName }}
  timeoutInMinutes: 120
  workspace:
    clean: all
  pool:
    name: ${{ parameters.AgentPool }}
    demands: ${{ parameters.AgentDemands }}
  variables:
    buildDirectory: '$(Build.BinariesDirectory)'
    BuildCommand: ${{ parameters.BuildCommand }}
    OnnxRuntimeBuildDirectory: '$(Build.BinariesDirectory)'
    DotNetExe: 'dotnet.exe'
    CUDA_VERSION: ${{ parameters.CudaVersion }}

  steps:
    - template: set-test-data-variables-step.yml
    - template: windows-build-tools-setup-steps.yml
      parameters:
        EnvSetupScript: ${{ parameters.EnvSetupScript }}
        buildArch: ${{ parameters.msbuildArchitecture }}
        setVcvars: ${{ parameters.SetVcvars }}
    - template: win-ci-helper.yml
      parameters:
        BuildCommand: $(BuildCommand)
        DoDebugBuild: ${{ parameters.DoDebugBuild }}
        DoNugetPack : ${{ parameters.DoNugetPack }}
        DoCompliance: ${{ parameters.DoCompliance }}
        DoEsrp: ${{ parameters.DoEsrp }}
        NuPackScript: ${{ parameters.NuPackScript }}
        ArtifactName: ${{ parameters.ArtifactName }}
        DoTestCoverage: ${{ parameters.DoTestCoverage }}
        BuildArch: ${{ parameters.BuildArch }}
        msbuildArchitecture: ${{ parameters.msbuildArchitecture }}
        MsbuildArguments: ${{ parameters.MsbuildArguments }}
        CudaVersion: ${{ parameters.CudaVersion }}
        OrtPackageId: ${{ parameters.OrtPackageId }}