jobs:
- job: Linux_OpenVINO_GPU_Nightly
  timeoutInMinutes: 360
  pool: OpenVINO
  steps:
    - task: CmdLine@2
      displayName: 'Clean untagged docker images'
      inputs:
        script: |
          docker rm $(docker ps -a | grep Exited | awk '{print $1;}') || true
          docker images -q --filter "dangling=true" | xargs -n1 -r docker rmi
        workingDirectory: $(Build.BinariesDirectory)
      continueOnError: true
      condition: always()
        
    - script: 'tools/ci_build/github/linux/run_dockerbuild.sh -o ubuntu16.04 -d openvino -v 2020.4 -r $(Build.BinariesDirectory) -x "--use_openvino GPU_FP32 --build_wheel"'
      displayName: 'Command Line Script'

    - template: templates/component-governance-component-detection-steps.yml
      parameters :
        condition : 'ci_only'

    - template: templates/clean-agent-build-directory-step.yml
