trigger: none

jobs:
- job: Onnxruntime_Linux_Multi_GPU_Test
  pool: Linux-Multi-GPU-V100

  timeoutInMinutes: 0

  steps:
  - checkout: self
    clean: true
    submodules: recursive

  - script: |
      tools/ci_build/github/linux/run_dockerbuild.sh \
        -o ubuntu16.04 -d gpu -r $(Build.BinariesDirectory) \
        -x " \
          --config RelWithDebInfo \
          --enable_training \
          --update --build \
          "
    displayName: 'Build'

  - script: |
      docker run \
        --gpus all \
        --rm \
        --volume $(Build.SourcesDirectory):/onnxruntime_src \
        --volume $(Build.BinariesDirectory):/build \
        onnxruntime-ubuntu16.04-cuda10.1-cudnn7.6 \
          /onnxruntime_src/orttraining/tools/ci_test/run_multi_gpu_test.py \
            --binary_dir /build/RelWithDebInfo 
    displayName: 'Run convergence test'
    condition: succeededOrFailed() # ensure all tests are run

  - template: templates/clean-agent-build-directory-step.yml
