trigger: none

jobs:
- template: templates/linux-ci.yml
  parameters:
    AgentPool : 'Linux-GPU-CUDA10'
    JobName: 'Onnxruntime_Linux_GPU_Training'
    SubmoduleCheckoutMode: 'recursive'
    OrtTrainingPrepareTestData: 'true'
    OrtTrainingPrepareTestDataCommand: >
      orttraining/tools/ci_test/download_e2e_test_data.py
      --azure_blob_url https://onnxruntimetestdata.blob.core.windows.net/training/glue_data.zip
      --target_dir /bert_data/hf_data/
    BuildCommand: >
      tools/ci_build/github/linux/run_dockerbuild.sh
      -o ubuntu16.04 -d gpu -r $(Build.BinariesDirectory)
      -x "
      --enable_training
      --config $(buildConfig)
      --build_wheel
      --enable_nvtx_profile
      "
    DoNugetPack: 'false'
    ArtifactName: 'drop-linux'
    TimeoutInMinutes: 90
    # Enable unreleased onnx opsets in CI builds
    # This facilitates testing the implementation for the new opsets
    AllowReleasedOpsetOnly: '0'
    Strategy: 
      maxParallel: 2
      matrix:
        Debug:
          buildConfig: Debug
        Release:
          buildConfig: Release

