parameters:
  packageFolder: $(Build.ArtifactStagingDirectory)

steps:
- task: CmdLine@2
  condition: eq(variables['Agent.OS'], 'Windows_NT')
  displayName: 'Extract version number from the NuPkg file, Windows VMs'
  inputs:
    workingDirectory: '${{ parameters.packageFolder }}'
    script: |
      @echo processing nupkg
      pwd
      dir
      SETLOCAL ENABLEDELAYEDEXPANSION
      FOR /R %%i IN (Microsoft.ML.OnnxRuntime*.nupkg) do (
        set filename=%%~ni
        @echo FileName is %filename%
        set ortversion=%filename:~25%
        @echo ortversion is %ortversion%
        @echo ##vso[task.setvariable variable=NuGetPackageVersionNumber;]%ortversion%
      )
      @echo "NugetPackageVersionNumber = $(NuGetPackageVersionNumber)"

- task: CmdLine@2
  condition: not(eq(variables['Agent.OS'], 'Windows_NT'))
  displayName: 'Extract version number from the NuPkg file, Unix VMs'
  inputs:
    workingDirectory: '${{ parameters.packageFolder }}'
    script: |
      filenamewithext=$(ls Microsoft.ML.OnnxRuntime*.nupkg)
      filename=${filenamewithext%.*}
      ortversion=${filename:25}
      echo "##vso[task.setvariable variable=NuGetPackageVersionNumber;]$ortversion"
