parameters:
  DoEsrp: 'false'
  PackageName: 'Microsoft.AI.MachineLearning'

jobs:
- job: WindowsAI_DirectML_X64
  timeoutInMinutes: 120
  workspace:
    clean: all
  pool:
    name: 'Win-GPU-2019'
    demands: []
  steps:
  - template: ../../templates/windowsai-nuget-build.yml
    parameters:
      BuildArch: 'x64'

- job: WindowsAI_DirectML_X86
  timeoutInMinutes: 120
  workspace:
    clean: all
  pool:
    name: 'Win-GPU-2019'
    demands: []
  steps:
  - template: ../../templates/windowsai-nuget-build.yml
    parameters:
      BuildArch: 'x86'

#- job: WindowsAI_DirectML_ARM64
#  timeoutInMinutes: 120
#  workspace:
#    clean: all
#  pool:
#    name: 'Win-CPU-2019'
#    demands: []
#  steps:
#  - template: ../../templates/windowsai-nuget-build.yml
#    parameters:
#      BuildArch: 'arm64'
#
#- job: WindowsAI_DirectML_ARM
#  timeoutInMinutes: 120
#  workspace:
#    clean: all
#  pool:
#    name: 'Win-CPU-2019'
#    demands: []
#  steps:
#  - template: ../../templates/windowsai-nuget-build.yml
#    parameters:
#      BuildArch: 'arm'

- job: NuGet_Packaging
  workspace:
    clean: all
  pool: 'Win-GPU-2019'
  dependsOn:
  - WindowsAI_DirectML_X64
  - WindowsAI_DirectML_X86
#  - WindowsAI_DirectML_ARM64
#  - WindowsAI_DirectML_ARM
  condition: succeeded()
  steps:
  - task: DownloadPipelineArtifact@0
    displayName: 'Download Pipeline Artifact - NuGet DirectML x64'
    inputs:
      artifactName: 'Microsoft.AI.MachineLearning.x64'
      targetPath: '$(Build.BinariesDirectory)/nuget-artifact-x64'

  - task: DownloadPipelineArtifact@0
    displayName: 'Download Pipeline Artifact - NuGet DirectML x86'
    inputs:
      artifactName: 'Microsoft.AI.MachineLearning.x86'
      targetPath: '$(Build.BinariesDirectory)/nuget-artifact-x86'

#  - task: DownloadPipelineArtifact@0
#    displayName: 'Download Pipeline Artifact - NuGet DirectML ARM64'
#    inputs:
#      artifactName: 'Microsoft.AI.MachineLearning.arm64'
#      targetPath: '$(Build.BinariesDirectory)/nuget-artifact-arm64'

#  - task: DownloadPipelineArtifact@0
#    displayName: 'Download Pipeline Artifact - NuGet DirectML ARM'
#    inputs:
#      artifactName: 'Microsoft.AI.MachineLearning.arm'
#      targetPath: '$(Build.BinariesDirectory)/nuget-artifact-arm'

  - task: PowerShell@2
    displayName: 'Bundle NuGet and other binaries (1)'
    inputs:
      targetType: 'inline'
      script: |
        Add-Type -AssemblyName "System.IO.Compression.FileSystem"

        $packages = (Get-ChildItem -Filter Microsoft.AI.MachineLearning* -Recurse)
        $x64_nuget_package_name = $packages[0].Name
        $x64_nuget_package = $packages[0].FullName
        $x64_unzipped_directory_root = $packages[0].Directory.FullName
        $x64_unzipped_directory = [System.IO.Path]::Combine($x64_unzipped_directory_root, [System.IO.Path]::GetFileNameWithoutExtension($x64_nuget_package))
        [System.IO.Compression.ZipFile]::ExtractToDirectory($x64_nuget_package, $x64_unzipped_directory)
        
        $packages = (Get-ChildItem ..\nuget-artifact-x86 -Filter Microsoft.AI.MachineLearning* -Recurse)
        $x86_nuget_package = $packages[0].FullName
        $x86_unzipped_directory_root = $packages[0].Directory.FullName
        $x86_unzipped_directory = [System.IO.Path]::Combine($x86_unzipped_directory_root, [System.IO.Path]::GetFileNameWithoutExtension($x86_nuget_package))
        [System.IO.Compression.ZipFile]::ExtractToDirectory($x86_nuget_package, $x86_unzipped_directory)

        $x86_runtime_path_old = [System.IO.Path]::Combine($x86_unzipped_directory, 'runtimes', 'win-x86', 'native')
        $x86_runtime_path_new = [System.IO.Path]::Combine($x64_unzipped_directory, 'runtimes', 'win-x86', 'native')
        New-Item -Path $x86_runtime_path_new -ItemType Directory

        Copy-Item ([System.IO.Path]::Combine($x86_runtime_path_old, 'onnxruntime.dll'))                   $x86_runtime_path_new
        Copy-Item ([System.IO.Path]::Combine($x86_runtime_path_old, 'onnxruntime.lib'))                   $x86_runtime_path_new
        Copy-Item ([System.IO.Path]::Combine($x86_runtime_path_old, 'onnxruntime.pdb'))                   $x86_runtime_path_new
        Copy-Item ([System.IO.Path]::Combine($x86_runtime_path_old, 'microsoft.ai.machinelearning.dll'))  $x86_runtime_path_new
        Copy-Item ([System.IO.Path]::Combine($x86_runtime_path_old, 'microsoft.ai.machinelearning.lib'))  $x86_runtime_path_new
        Copy-Item ([System.IO.Path]::Combine($x86_runtime_path_old, 'microsoft.ai.machinelearning.pdb'))  $x86_runtime_path_new
        Copy-Item ([System.IO.Path]::Combine($x86_runtime_path_old, 'directml.dll'))                      $x86_runtime_path_new

        Get-ChildItem env:
        
        $merged_nuget = [System.IO.Path]::Combine($x64_unzipped_directory_root, 'merged', $x64_nuget_package_name)
        [System.IO.Compression.ZipFile]::CreateFromDirectory($x64_unzipped_directory, $merged_nuget)
      workingDirectory: $(Build.BinariesDirectory)\nuget-artifact-x64

  - script: |
     pushd $(Build.BinariesDirectory)\nuget-artifact
     dir
     powershell -Command "Invoke-WebRequest http://stahlworks.com/dev/unzip.exe -OutFile unzip.exe"
     powershell -Command "Invoke-WebRequest http://stahlworks.com/dev/zip.exe -OutFile zip.exe"
     set PATH=%CD%;%PATH%
     FOR /R %%i IN (*.nupkg) do (
         rename %%~ni.nupkg %%~ni.zip
         unzip %%~ni.zip -d %%~ni
         del /Q %%~ni.zip

         unzip Microsoft.AI.MachineLearning.x86.zip -d win-x86
         unzip Microsoft.AI.MachineLearning.arm64.zip -d win-arm64
         unzip Microsoft.AI.MachineLearning.arm.zip -d win-arm

         mkdir %%~ni\runtimes\win-x86
         mkdir %%~ni\runtimes\win-x86\native
         mkdir %%~ni\runtimes\win-arm64
         mkdir %%~ni\runtimes\win-arm64\native
         mkdir %%~ni\runtimes\win-arm
         mkdir %%~ni\runtimes\win-arm\native

         move win-x86\runtimes\win-x86\native\onnxruntime.dll %%~ni\runtimes\win-x86\native\onnxruntime.dll
         move win-x86\runtimes\win-x86\native\onnxruntime.lib %%~ni\runtimes\win-x86\native\onnxruntime.lib
         move win-x86\runtimes\win-x86\native\onnxruntime.pdb %%~ni\runtimes\win-x86\native\onnxruntime.pdb

         move win-x86\runtimes\win-x86\native\microsoft.ai.machinelearning.dll %%~ni\runtimes\win-x86\native\microsoft.ai.machinelearning.dll
         move win-x86\runtimes\win-x86\native\microsoft.ai.machinelearning.lib %%~ni\runtimes\win-x86\native\microsoft.ai.machinelearning.lib
         move win-x86\runtimes\win-x86\native\microsoft.ai.machinelearning.pdb %%~ni\runtimes\win-x86\native\microsoft.ai.machinelearning.pdb

         move win-x86\runtimes\win-x86\native\directml.dll %%~ni\runtimes\win-x86\native\directml.dll

         pushd %%~ni
         zip -r ..\%%~ni.zip .
         popd
         move %%~ni.zip %%~ni.nupkg
     )
     popd
     copy $(Build.BinariesDirectory)\nuget-artifact\Microsoft.AI.MachineLearning*nupkg $(Build.ArtifactStagingDirectory)
    displayName: 'Bundle NuGet and other binaries'

  - template: ../../templates/esrp_nuget.yml
    parameters:
      DisplayName: 'ESRP - sign NuGet package'
      FolderPath: '$(Build.ArtifactStagingDirectory)'
      DoEsrp: ${{ parameters.DoEsrp }}

  - template: ../../templates/validate-nuget.yml
    parameters:
      NugetPath: '$(Build.ArtifactStagingDirectory)'
      NugetPackage: 'Microsoft.AI.MachineLearning*nupkg'
      PlatformsSupported: 'win-x64,win-x86'
      #,win-arm64,win-arm'
      VerifyNugetSigning: ${{ parameters.DoEsrp }}


  - task: PublishPipelineArtifact@0
    displayName: 'Publish Pipeline NuGet Artifact'
    inputs:
      artifactName: 'drop-signed-nuget'
      targetPath: '$(Build.ArtifactStagingDirectory)'

- template: test_win.yml
  parameters:
    AgentPool : 'Win-GPU-2019'
    Skipx86Tests: 'true'
