parameters:
  DoEsrp: 'false'

jobs:
- template: ../../templates/win-ci-2019.yml
  parameters:
    AgentPool : 'Win-GPU-2019'
    ArtifactName: 'drop-nuget-trt'
    JobName: 'Windows_CI_GPU_TensorRT_Dev'
    BuildCommand: --build_dir $(Build.BinariesDirectory) --skip_submodule_sync --build_shared_lib --update --cmake_generator "Visual Studio 16 2019" --msvc_toolset 14.16 --build_wheel --enable_onnx_tests --use_tensorrt --tensorrt_home="C:\local\TensorRT-7.0.0.11.cuda-10.2.cudnn7.6\TensorRT-7.0.0.11" --cuda_version=10.2 --cuda_home="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2" --cudnn_home="C:\local\cudnn-10.2-windows10-x64-v7.6.5.32\cuda" --cmake_extra_defines CMAKE_SYSTEM_VERSION=10.0.18362.0
    BuildArch: 'x64'
    msbuildArchitecture: 'amd64'
    EnvSetupScript: 'setup_env_trt.bat'
    sln_platform: 'x64'
    DoDebugBuild: 'false'
    DoNugetPack : 'false'
    DoCompliance: 'false'
    DoEsrp: ${{ parameters.DoEsrp }}
    CudaVersion: '10.2'
    OrtPackageId: 'Microsoft.ML.OnnxRuntime'